SELECT TOP 1000 [PaymentID]
,[PointID]
,[TransactionID]
,[TryNumber]
,[UserID]
,[PointDeviceID]
,[ReceiptNumber]
,[PayTime]
,[CreateTime]
,[StatusTime]
,[ProcessedTime]
,[ProviderTime]
,[IP]
,[ServiceID]
,[ProviderID]
,[ProtocolID]
,[OuterTransactionID]
,[ProviderTransactionID]
,[Number]
,[PayType]
,[Status]
,[Code]
,[ProcessStatus]
,[PayValue]
,[ServiceValue]
,[SalesTax]
,[CurrencyID]
,[ToCurrencyID]
,[ToPayValue]
,[ToServiceValue]
,[ProviderProfit]
,[ProviderProfitValue]
,[ProviderCommissionValue]
,[RevokeStatus]
,[RevokeStatusTime]
,[RevokeUserID]
,[RevokeValue]
,[RetryStatus]
,[RetryUserID]
,[RetryTime]
,[FromPaymentID]
,[ToPaymentID]
,[Refunded]
,[RefundedTime]
,[RefundedUserID]
,[ProcessTryCount]
,[ProcessTryTime]
,[ProcessNextTryTime]
,[PaymentInfo]
,[Comment]
,[HasPointExtra]
,[HasServiceExtra]
,[HasPinCodes]
,[HasVouchersIn]
,[HasVouchersOut]
,[Online]
,[IsNonFinancial]
,[IsConfirmed]
,[IsConfirmedDate]
,[IsPinActivated]
,[TaxInvoiceID]
,[ToChangeAccountID]
,[ToChangeAccountValue]
,[ToChangeAccountCommitedValue]
,[CashOutID]
,[PortalComment]
,[IsFishing]
,[ActivityID]
,[PaymentSchemeID]
FROM [Main].[dbo].[Payment] with (nolock)
Where ServiceID in (1083,1084,1007,1119)
and (RevokeStatusTime between '2020-08-01' and '2020-09-01') --and CreateTime  between '2020-08-01' and '2020-09-01'
and RevokeStatus in (4,5)


