select 
	 [PaymentID]
      ,[PointID]
      ,[TransactionID]
      ,[UserID]
      ,[PayTime]
      ,[CreateTime]
      ,[StatusTime]
      ,[Number]
      ,[PayValue]
      ,[ServiceValue]
	  ,'0' ConvFeeMpay
      ,'0'  [ConvFee]
      ,[Status]
      ,[Code]
      ,[ProcessStatus]
      ,[PayType]
      ,'' [PayTypeName]
      ,[ServiceID]
      ,'' [ServiceName]
      ,'' [UserName]
      ,'' [DealerID]
      ,'' [DealerName]
      ,[OuterTransactionID]
      ,'' [StatusName]
      ,'' [USD_PayValue]
      ,'' [USD_ServiceValue]
      ,[ReceiptNumber]
      , '0' as [PointName]
      ,'' [UserEnabled]
      ,'' [PointEnabled]
      ,'' [DealerEnabled]
      ,[ProcessTryCount]
      ,[ProcessTryTime]
      ,'' [CodeName]
      ,'' [UserPointID]
      ,'' [Retried]
      ,[RetryStatus]
      ,'' [RetryStatusName]
      ,[RetryTime]
      ,[FromPaymentID]
      ,[ToPaymentID]
      ,'' [RetryTime1]
      ,[RetryUserID]
      ,'' [RetryUserName]
      ,[RevokeStatus]
      ,'' [RevokeStatusName]
	  ,'0' [RevokeValueMpay]
	  ,'0'[RevokeValue]
      
      ,'' [USD_RevokeValue]
      ,[RevokeUserID]
      ,'' [RevokeUserName]
      ,[Refunded]
      ,[RefundedTime]
      ,[RefundedUserID]
      ,'' [RefundedUserName]
      ,'' [UseConfirmation]
      ,[IsConfirmed]
      ,[IsConfirmedDate]
      ,'' [CanChangeConfirmationStatus]
      ,'' [PointType]
      ,'' [PointAddressCode]
      ,'' [Name]
      ,'' [AllowRetry]
      ,'' [AllowRefund]
      ,'' [AllowRefundCancel]
      ,'0' as [Comment]
	  ,'0' as [PortalComment]
      ,'' [NomenclatureID]
      ,'' [NomenclatureName]
      ,'' [NomenclatureCode]
      ,'' [CardPaymentStatus]
      ,'' [CardPaymentStatusName]
	  ,'' as IsFishing 
	  ,'' [RevokeTime]



 from Main.dbo.Payment where PaymentID=469295550
