/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [PaymentID]
      ,[AgentPaymentID]
      ,[ServiceID]
      ,[GateServiceID]
      ,[PayDate]
      ,[AgentDate]
      ,[ReceiveDate]
      ,[WaitToDate]
      ,[StatusDate]
      ,[Number]
      ,[AgentTerminalID]
      ,[PaySum]
      ,[ProviderSum]
      ,[CommissionSum]
      ,[Status]
      ,[Code]

      ,[GateNextTryDate]

      ,[AgentReceipteDate]
      ,[AgentReceipteNumber]
      ,[ProviderDateTimeZoneID]
      ,[OsmpProviderID]
  FROM [May_2019].[dbo].[eTopazM2]
