---RevokedPayments

 SELECT  * from TURALTEST.[dbo].[RejectedPayments] a where 
len (RetryStatusName) >13 and DealerName not like '%Kassam.az%' and DealerName not like '%test%'

and Name like '%OSMP_STATUS_WINDOWS_TERMINAL_OSMP%' and RevokeStatusName like '%OSMP_STATUS_REV_SUCCESS%'

union all

---RevokedPayments

SELECT *
  FROM [TURALTEST].[dbo].[PartialPayments] where ServiceValue!=RevokeValue and Month(CreateTime)=10---bu ay


------------------------------------------------------------------------


---RevokedPayments 

SELECT [PaymentID]
      ,[PointID]
      ,[TransactionID]
      ,[UserID]
      ,[PayTime]
      ,[CreateTime]
      ,[StatusTime]
      ,[Number]
      ,[PayValue]
      ,[ServiceValue]
      ,[ConvFee]
      ,[Status]
      ,[Code]
      ,[ProcessStatus]
      ,[PayType]
      ,[PayTypeName]
      ,[ServiceID]
      ,[ServiceName]
      ,[UserName]
      ,[DealerID]
      ,[DealerName]
      ,[OuterTransactionID]
      ,[StatusName]
      ,[USD_PayValue]
      ,[USD_ServiceValue]
      ,[ReceiptNumber]
      ,[PointName]
      ,[UserEnabled]
      ,[PointEnabled]
      ,[DealerEnabled]
      ,[ProcessTryCount]
      ,[ProcessTryTime]
      ,[CodeName]
      ,[UserPointID]
      ,[Retried]
      ,[RetryStatus]
      ,[RetryStatusName]
      ,[RetryTime]
      ,[FromPaymentID]
      ,[ToPaymentID]
      ,[RetryTime1]
      ,[RetryUserID]
      ,[RetryUserName]
      ,[RevokeStatus]
      ,[RevokeStatusName]
      ,[RevokeTime]
      ,[RevokeValue]
      ,[USD_RevokeValue]
      ,[RevokeUserID]
      ,[RevokeUserName]
      ,[Refunded]
      ,[RefundedTime]
      ,[RefundedUserID]
      ,[RefundedUserName]
      ,[UseConfirmation]
      ,[IsConfirmed]
      ,[IsConfirmedDate]
      ,[CanChangeConfirmationStatus]
      ,[PointType]
      ,[PointAddressCode]
      ,[Name]
      ,[AllowRetry]
      ,[AllowRefund]
      ,[AllowRefundCancel]
      ,[Comment]
      --, ASCII (RIGHT(,1) ) 
	  ,REPLACE(REPLACE(REPLACE([PortalComment], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,'')as [PortalComment]
      , [NomenclatureID]
      ,[NomenclatureName]
      ,[NomenclatureCode]
      ,[CardPaymentStatus]
      ,[CardPaymentStatusName]
	  ,'' as IsFishing
  FROM [TURALTEST].[dbo].RusRevokedPayments m where PaymentID not in (select PaymentID from  (select PaymentID,Month from  REJECTED.[dbo].PerRevokedCurrentMonth r1 union all  select PaymentID,Month from  REJECTED.[dbo].PerRevokedPayments r2) k  where k.Month < m.Month)

SELECT [PaymentID]
      ,[PointID]
      ,[TransactionID]
      ,[UserID]
      ,[PayTime]
      ,[CreateTime]
      ,[StatusTime]
      ,[Number]
      ,[PayValue]
      ,[ServiceValue]
      ,[ConvFee]
      ,[Status]
      ,[Code]
      ,[ProcessStatus]
      ,[PayType]
      ,[PayTypeName]
      ,[ServiceID]
      ,[ServiceName]
      ,[UserName]
      ,[DealerID]
      ,[DealerName]
      ,[OuterTransactionID]
      ,[StatusName]
      ,[USD_PayValue]
      ,[USD_ServiceValue]
      ,[ReceiptNumber]
      ,[PointName]
      ,[UserEnabled]
      ,[PointEnabled]
      ,[DealerEnabled]
      ,[ProcessTryCount]
      ,[ProcessTryTime]
      ,[CodeName]
      ,[UserPointID]
      ,[Retried]
      ,[RetryStatus]
      ,[RetryStatusName]
      ,[RetryTime]
      ,[FromPaymentID]
      ,[ToPaymentID]
      ,[RetryTime1]
      ,[RetryUserID]
      ,[RetryUserName]
      ,[RevokeStatus]
      ,[RevokeStatusName]
      ,[RevokeTime]
      ,[RevokeValue]
      ,[USD_RevokeValue]
      ,[RevokeUserID]
      ,[RevokeUserName]
      ,[Refunded]
      ,[RefundedTime]
      ,[RefundedUserID]
      ,[RefundedUserName]
      ,[UseConfirmation]
      ,[IsConfirmed]
      ,[IsConfirmedDate]
      ,[CanChangeConfirmationStatus]
      ,[PointType]
      ,[PointAddressCode]
      ,[Name]
      ,[AllowRetry]
      ,[AllowRefund]
      ,[AllowRefundCancel]
      ,[Comment]
      --, ASCII (RIGHT(,1) ) 
	  ,REPLACE(REPLACE(REPLACE([PortalComment], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,'')as [PortalComment]
      , [NomenclatureID]
      ,[NomenclatureName]
      ,[NomenclatureCode]
      ,[CardPaymentStatus]
      ,[CardPaymentStatusName]
	  ,'' as IsFishing
  FROM [TURALTEST].[dbo].YarRevokedPayments m where PaymentID not in (select PaymentID from  (select PaymentID,Month from  REJECTED.[dbo].PerRevokedCurrentMonth r1 union all  select PaymentID,Month from  REJECTED.[dbo].PerRevokedPayments r2) k  where k.Month < m.Month)
