[PaymentID]
      ,'' [PointID]
      ,[TransactionID]
      ,'' [UserID]
      ,[PayTime]
      ,[CreateTime]
      ,[StatusTime]
      ,[Number]
      ,[PayValue]
      ,'' [ServiceValue]
	  ,case when DealerID =16 then [ConvFee] else '0.00' end ConvFeeMpay
      ,case when DealerID !=16 then [ConvFee] else '0.00' end [ConvFee]
      ,[Status]
      ,'' [Code]
      ,'' [ProcessStatus]
      ,'' [PayType]
      ,'' [PayTypeName]
      ,[ServiceID]
      
	  , ''  [ServiceName] --REPLACE(REPLACE(REPLACE([ServiceName], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,'')as [ServiceName]
      ,'' [UserName]
      ,[DealerID]

	  , -- REPLACE(REPLACE(REPLACE([DealerName], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,'')as
	   '' [DealerName]
      ,'' [OuterTransactionID]
      ,''  [StatusName]
      ,'' [USD_PayValue]
      ,'' [USD_ServiceValue]
      ,'' [ReceiptNumber]
      , --REPLACE(REPLACE(REPLACE([PointName], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,'')as 
	  '' [PointName]
      ,'' [UserEnabled]
      ,'' [PointEnabled]
      ,'' [DealerEnabled]
      ,'' [ProcessTryCount]
      ,'' [ProcessTryTime]
      ,'' [CodeName]
      ,'' [UserPointID]
      ,'' [Retried]
      ,'' [RetryStatus]
      ,'' [RetryStatusName]
      ,'' [RetryTime]
      ,'' [FromPaymentID]
      ,'' [ToPaymentID]
      ,'' [RetryTime1]
      ,'' [RetryUserID]
      ,'' [RetryUserName]
      ,'' [RevokeStatus]
      ,'' [RevokeStatusName]
	  ,case when DealerID =16 then [RevokeValue] else '0.00' end [RevokeValueMpay]
	  ,case when DealerID !=16 then [RevokeValue] else '0.00' end [RevokeValue]
      
      ,'' [USD_RevokeValue]
      ,'' [RevokeUserID]
      ,'' [RevokeUserName]
      ,'' [Refunded]
      ,'' [RefundedTime]
      ,'' [RefundedUserID]
      ,'' [RefundedUserName]
      ,'' [UseConfirmation]
      ,'' [IsConfirmed]
      ,'' [IsConfirmedDate]
      ,'' [CanChangeConfirmationStatus]
      ,'' [PointType]
      ,'' [PointAddressCode]
      ,'' [Name]
      ,'' [AllowRetry]
      ,'' [AllowRefund]
      ,'' [AllowRefundCancel]
      ,case when [Comment] is null then  '' else REPLACE (REPLACE(REPLACE(REPLACE([Comment], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,''), ' ','') end as [Comment]
	  ,case when [PortalComment] is null then  '' else  REPLACE (REPLACE(REPLACE(REPLACE([PortalComment], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,''), ' ','') end as [PortalComment]
      ,[NomenclatureID]
      ,REPLACE (REPLACE(REPLACE(REPLACE([NomenclatureName], CHAR(13), ''), CHAR(10), ''),CHAR(9) ,''), ' ','&')  [NomenclatureName]
      ,'' [NomenclatureCode]
      ,'' [CardPaymentStatus]
      ,'' [CardPaymentStatusName]
	  ,'' as IsFishing 
	  ,[RevokeTime]
