SELECT count(*) tekrar_sayi, [TOTAL_AMOUNT]
      ,[REF_NUM]
      ,[trn]
      ,[PaySum]
      ,[status]
  FROM [Noyabr2020].[dbo].[zennerjoin]
  group by [TOTAL_AMOUNT]
      ,[REF_NUM]
      ,[trn]
      ,[PaySum]
      ,[status]
